# File: .github/workflows/run-python.yml

name: Run Basic Python Script

on: [push]  # Run this workflow every time you push

jobs:
  run-basic-python:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Run Python Script
      run: python python.py
